; SpeakerBox Pro — ESP32-S3 Firmware
; Board: ESP32-S3-WROOM-1-N8R2 (8 MB Flash, 2 MB PSRAM)

[env:speakerbox]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; 8 MB Flash: 2 App-Partitionen (OTA) + LittleFS fuer die Web-App
board_build.partitions = partitions_ota_8mb.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_qspi

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=2

lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    adafruit/Adafruit NeoPixel@^1.12.0
    olikraus/U8g2@^2.35.19
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    esphome/AsyncTCP-esphome@^2.1.4
