M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Tue Jul  7 08:58:30 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-07T08:58:30+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X94.4Y-49.11
X94.4Y-54.89
T2
X4.5Y-72.0
X11.5Y-72.0
T3
X4.0Y-43.0
X4.0Y-58.0
X52.0Y-5.0
X96.5Y-28.0
M30
